export const cardDescriptions: Record<string, string> = {
  "Hybrid Reasoning": "Advanced cognitive methods enabling deep logic, step-by-step problem solving, and deductive inference across complex domains.",
  "Coding Agents": "Specialized models fine-tuned for software engineering, autonomous code generation, syntax debugging, and logic compilation.",
  "Tool Use": "State-of-the-art implementations focusing on tool use, providing foundational tools for complex autonomous workflows.",
  "Multimodal": "Unified foundation models capable of natively processing text, audio, and visual streams simultaneously for holistic understanding.",
  "Reasoning": "Advanced cognitive methods enabling deep logic, step-by-step problem solving, and deductive inference across complex domains.",
  "Realtime Audio": "Models optimized for continuous speech recognition, high-fidelity audio synthesis, and real-time voice translation.",
  "Reinforcement Learning": "Innovative machine learning methodologies targeting reinforcement learning to deliver robust, scalable, and highly efficient AI solutions.",
  "Math": "Precision-driven algorithms trained to solve advanced mathematical proofs, complex algebraic equations, and quantitative reasoning.",
  "Agentic AI": "Intelligent systems designed for autonomous task execution, continuous planning, and dynamic real-world environment interaction.",
  "Long Context": "State-of-the-art implementations focusing on long context, providing foundational tools for complex autonomous workflows.",
  "Open Weight": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in open weight.",
  "Language Modeling": "Innovative machine learning methodologies targeting language modeling to deliver robust, scalable, and highly efficient AI solutions.",
  "Distillation": "Dedicated engineering and algorithmic breakthroughs enabling unprecedented precision and recall within distillation systems.",
  "MoE": "Pioneering research and deployment strategies that harness moe for next-generation generative applications.",
  "Math & Code": "Precision-driven algorithms trained to solve advanced mathematical proofs, complex algebraic equations, and quantitative reasoning.",
  "Bilingual": "Innovative machine learning methodologies targeting bilingual to deliver robust, scalable, and highly efficient AI solutions.",
  "Realtime Search": "State-of-the-art implementations focusing on realtime search, providing foundational tools for complex autonomous workflows.",
  "Large Scale": "State-of-the-art implementations focusing on large scale, providing foundational tools for complex autonomous workflows.",
  "Robotics": "State-of-the-art implementations focusing on robotics, providing foundational tools for complex autonomous workflows.",
  "Embodied AI": "State-of-the-art implementations focusing on embodied ai, providing foundational tools for complex autonomous workflows.",
  "VLA": "Pioneering research and deployment strategies that harness vla for next-generation generative applications.",
  "SWE-bench": "Dedicated engineering and algorithmic breakthroughs enabling unprecedented precision and recall within swe-bench systems.",
  "Function Calling": "Advanced computational approaches leveraging deep neural networks to push the boundaries of function calling capabilities.",
  "Multilingual": "Pioneering research and deployment strategies that harness multilingual for next-generation generative applications.",
  "Code Generation": "Innovative machine learning methodologies targeting code generation to deliver robust, scalable, and highly efficient AI solutions.",
  "Small Language Model": "Dedicated engineering and algorithmic breakthroughs enabling unprecedented precision and recall within small language model systems.",
  "Synthetic Data": "State-of-the-art implementations focusing on synthetic data, providing foundational tools for complex autonomous workflows.",
  "Image Generation": "State-of-the-art implementations focusing on image generation, providing foundational tools for complex autonomous workflows.",
  "Flow Matching": "State-of-the-art implementations focusing on flow matching, providing foundational tools for complex autonomous workflows.",
  "Diffusion": "Pioneering research and deployment strategies that harness diffusion for next-generation generative applications.",
  "Computer Vision": "State-of-the-art architectures designed to process, interpret, and generate high-fidelity visual content and complex imagery.",
  "Video Tracking": "Temporal architectures built to analyze video sequences, track moving objects, and generate consistent motion graphics.",
  "Segmentation": "Advanced computational approaches leveraging deep neural networks to push the boundaries of segmentation capabilities.",
  "Speech-to-Text": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in speech-to-text.",
  "Audio Recognition": "Models optimized for continuous speech recognition, high-fidelity audio synthesis, and real-time voice translation.",
  "Efficient Attention": "Innovative machine learning methodologies targeting efficient attention to deliver robust, scalable, and highly efficient AI solutions.",
  "MMDiT": "State-of-the-art implementations focusing on mmdit, providing foundational tools for complex autonomous workflows.",
  "Agentic Coding": "Specialized models fine-tuned for software engineering, autonomous code generation, syntax debugging, and logic compilation.",
  "STEM": "Innovative machine learning methodologies targeting stem to deliver robust, scalable, and highly efficient AI solutions.",
  "Chain of Thought": "Pioneering research and deployment strategies that harness chain of thought for next-generation generative applications.",
  "RL": "Advanced computational approaches leveraging deep neural networks to push the boundaries of rl capabilities.",
  "Advanced Coding": "Specialized models fine-tuned for software engineering, autonomous code generation, syntax debugging, and logic compilation.",
  "World Knowledge": "Dedicated engineering and algorithmic breakthroughs enabling unprecedented precision and recall within world knowledge systems.",
  "Nuanced Reasoning": "Advanced cognitive methods enabling deep logic, step-by-step problem solving, and deductive inference across complex domains.",
  "Conversation": "State-of-the-art implementations focusing on conversation, providing foundational tools for complex autonomous workflows.",
  "Enterprise": "Innovative machine learning methodologies targeting enterprise to deliver robust, scalable, and highly efficient AI solutions.",
  "JSON Mode": "State-of-the-art implementations focusing on json mode, providing foundational tools for complex autonomous workflows.",
  "128k Context": "State-of-the-art implementations focusing on 128k context, providing foundational tools for complex autonomous workflows.",
  "Fast": "Advanced computational approaches leveraging deep neural networks to push the boundaries of fast capabilities.",
  "Cost Effective": "Dedicated engineering and algorithmic breakthroughs enabling unprecedented precision and recall within cost effective systems.",
  "Vision": "State-of-the-art architectures designed to process, interpret, and generate high-fidelity visual content and complex imagery.",
  "Preview": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in preview.",
  "Computer Use": "Dedicated engineering and algorithmic breakthroughs enabling unprecedented precision and recall within computer use systems.",
  "Coding Leader": "Specialized models fine-tuned for software engineering, autonomous code generation, syntax debugging, and logic compilation.",
  "High Velocity": "State-of-the-art implementations focusing on high velocity, providing foundational tools for complex autonomous workflows.",
  "Sub-second": "Innovative machine learning methodologies targeting sub-second to deliver robust, scalable, and highly efficient AI solutions.",
  "Coding": "Specialized models fine-tuned for software engineering, autonomous code generation, syntax debugging, and logic compilation.",
  "Multimodal Reasoning": "Advanced cognitive methods enabling deep logic, step-by-step problem solving, and deductive inference across complex domains.",
  "1M Context": "Pioneering research and deployment strategies that harness 1m context for next-generation generative applications.",
  "Flash Speed": "State-of-the-art implementations focusing on flash speed, providing foundational tools for complex autonomous workflows.",
  "2M Context": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in 2m context.",
  "Video Understanding": "Temporal architectures built to analyze video sequences, track moving objects, and generate consistent motion graphics.",
  "Vision-Language": "State-of-the-art architectures designed to process, interpret, and generate high-fidelity visual content and complex imagery.",
  "Document OCR": "Pioneering research and deployment strategies that harness document ocr for next-generation generative applications.",
  "Open Weights": "Innovative machine learning methodologies targeting open weights to deliver robust, scalable, and highly efficient AI solutions.",
  "Real-time Knowledge": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in real-time knowledge.",
  "Mathematics": "Precision-driven algorithms trained to solve advanced mathematical proofs, complex algebraic equations, and quantitative reasoning.",
  "General Purpose": "Advanced computational approaches leveraging deep neural networks to push the boundaries of general purpose capabilities.",
  "Agents": "Dedicated engineering and algorithmic breakthroughs enabling unprecedented precision and recall within agents systems.",
  "Video": "Temporal architectures built to analyze video sequences, track moving objects, and generate consistent motion graphics.",
  "Open Source": "State-of-the-art implementations focusing on open source, providing foundational tools for complex autonomous workflows.",
  "Document AI": "Pioneering research and deployment strategies that harness document ai for next-generation generative applications.",
  "Search": "Dedicated engineering and algorithmic breakthroughs enabling unprecedented precision and recall within search systems.",
  "Instruction Following": "State-of-the-art implementations focusing on instruction following, providing foundational tools for complex autonomous workflows.",
  "Small Language Models": "Pioneering research and deployment strategies that harness small language models for next-generation generative applications.",
  "GPT": "OpenAI's flagship series of generative pre-trained transformers, defining the frontier of general-purpose language and reasoning.",
  "Claude": "Anthropic's constitutional AI models, engineered for unparalleled safety, advanced coding, and nuanced contextual understanding.",
  "Gemini": "Google's natively multimodal ecosystem, built from the ground up to seamlessly integrate vision, text, and audio processing.",
  "Qwen": "State-of-the-art implementations focusing on qwen, providing foundational tools for complex autonomous workflows.",
  "Llama": "Meta's open-weight foundation models, democratizing access to state-of-the-art performance across diverse global deployments.",
  "Moonshot": "State-of-the-art implementations focusing on moonshot, providing foundational tools for complex autonomous workflows.",
  "GLM": "Advanced computational approaches leveraging deep neural networks to push the boundaries of glm capabilities.",
  "Mistral": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in mistral.",
  "Grok": "Innovative machine learning methodologies targeting grok to deliver robust, scalable, and highly efficient AI solutions.",
  "Gemma": "Innovative machine learning methodologies targeting gemma to deliver robust, scalable, and highly efficient AI solutions.",
  "Molmo": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in molmo.",
  "Anthropic": "AI safety and research company dedicated to building reliable, interpretable, and steerable frontier foundation systems.",
  "OpenAI": "Pioneering artificial general intelligence research lab responsible for the GPT ecosystem and breakthrough generative models.",
  "DeepSeek AI": "Advanced computational approaches leveraging deep neural networks to push the boundaries of deepseek ai capabilities.",
  "Google DeepMind": "Global technology leader driving fundamental AI research, from transformers to massive-scale multimodal architectures.",
  "Meta AI": "Championing the open-source AI ecosystem with accessible, high-performance weights bridging the gap between research and production.",
  "Alibaba Cloud": "State-of-the-art implementations focusing on alibaba cloud, providing foundational tools for complex autonomous workflows.",
  "xAI": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in xai.",
  "Mistral AI": "Advanced computational approaches leveraging deep neural networks to push the boundaries of mistral ai capabilities.",
  "Microsoft Research": "Innovative machine learning methodologies targeting microsoft research to deliver robust, scalable, and highly efficient AI solutions.",
  "Black Forest Labs": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in black forest labs.",
  "Stability AI": "State-of-the-art implementations focusing on stability ai, providing foundational tools for complex autonomous workflows.",
  "Moonshot AI": "Pioneering research and deployment strategies that harness moonshot ai for next-generation generative applications.",
  "Zhipu AI": "Advanced computational approaches leveraging deep neural networks to push the boundaries of zhipu ai capabilities.",
  "Allen Institute for AI": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in allen institute for ai.",
  "Robotics & VLA": "Advanced computational approaches leveraging deep neural networks to push the boundaries of robotics & vla capabilities.",
  "Vision & Generation": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in vision & generation.",
  "Audio & Speech": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in audio & speech.",
  "Multimodal AI": "Specialized architectures and training paradigms designed specifically to optimize performance and accuracy in multimodal ai.",
  "Large Language Models": "State-of-the-art implementations focusing on large language models, providing foundational tools for complex autonomous workflows.",
};
export function getCardDescription(name: string): string {
  return cardDescriptions[name] || `Advanced methodologies exploring ${name.toLowerCase()} to push the boundaries of modern artificial intelligence.`;
}
